import re

from logger_config import logger
from test_ask_vanna import vn 

def execute_analytical_plan(full_action_plan: str):
    """
    Executes a multi-step analytical plan generated by the Planner Agent.
    Dynamically resolves dependencies, extracts step-specific metadata, 
    and leverages Vanna's RAG capabilities for targeted SQL generation.
    """
    logger.info("Starting execution of the Vanna Plan...\n")
    
    # ---------------------------------------------------------
    # PHASE 1: Plan Parsing
    # Split the full plan into distinct steps using regex.
    # Matches "1. ... </sql_metadata>", "2. ... </sql_metadata>", etc.
    # ---------------------------------------------------------
    logger.debug(f"Action Plan:\n{full_action_plan}\n")
    step_blocks = re.findall(r'(\d+\.\s.*?(?:</sql_metadata>))', full_action_plan, re.DOTALL)
    logger.debug(f"Step Blocks: {step_blocks}\n")

    if not step_blocks:
        logger.error("Failed to parse action steps from the provided plan.")
        return {"error": "Could not parse actionable steps from the plan."}

    # Central memory dictionary to store the DataFrame results of each step.
    # This acts as the "bridge" for cross-step parameters.
    step_results_memory = {} 
    
    for i, step_text in enumerate(step_blocks):
        current_step_num = i + 1
        logger.info(f"--- Processing Step {current_step_num} ---")
        
        # ---------------------------------------------------------
        # PHASE 2: Metadata Extraction & Prompt Cleanup
        # Extract the <sql_metadata> block to find targeted 'Tables Used'
        # ---------------------------------------------------------
        match = re.search(r'<sql_metadata>(.*?)</sql_metadata>', step_text, re.DOTALL) # Find the metadata block within the step text
        content = match.group(1).strip() if match else ""
        specific_tables = re.sub(r'.*:\s*', '', content).strip() # Ensurre only get the table names only 

        if not specific_tables:
            logger.warning(f"No specific tables found for Step {current_step_num}. Vanna might hallucinate.")

        clean_step_text = re.sub(r'<sql_metadata>.*?</sql_metadata>', '', step_text, flags=re.DOTALL).strip() # Remove the metadata block, change to '' 

        # ---------------------------------------------------------
        # PHASE 3: Dynamic Dependency Resolution (Placeholder Replacement)
        # Find and replace matches like: [Found from Step 1: ChannelName]
        # ---------------------------------------------------------
        placeholders = re.findall(r"\[Found from Step (\d+): (.*?)\]", clean_step_text)
        logger.debug(f"{placeholders}\n")

        for source_step_str, column_name in placeholders:
            source_step = int(source_step_str)
            
            if source_step in step_results_memory:
                historical_df = step_results_memory[source_step]
                
                # Extract unique values from the target column
                if column_name in historical_df.columns:
                    logger.debug(   "historical_df: {historical_df}\n")
                    extracted_values = historical_df[column_name].dropna().unique().tolist()
                    logger.debug(f"Extrated value:{extracted_values}\n")

                    # Format values into a SQL-friendly IN clause string: "'Online', 'Store'"
                    sql_values_str = ", ".join([f"'{str(v)}'" for v in extracted_values])
                    
                    # Physically replace the placeholder tag in the text
                    target_tag = f"[Found from Step {source_step_str}: {column_name}]"
                    
                    # Change the placeholder from [Found from Step x: fieldname] to "FieldName IN ('x', 'x')"
                    meaningful_replacement = f"{column_name} IN ({sql_values_str})"

                    clean_step_text = clean_step_text.replace(target_tag, meaningful_replacement)
                else:
                    logger.error(f"Column '{column_name}' not found in Step {source_step} results!")
            else:
                logger.error(f"Results for Step {source_step} not found in memory!")

        logger.debug(f"\n\n\nTargeted Tables: {specific_tables}\n")
        logger.debug(f"Cleaned Task Description: {clean_step_text}\n\n\n")

        # ---------------------------------------------------------
        # PHASE 4: Custom Vanna RAG Assembly
        # We manually call Vanna's retrieval methods instead of generate_sql()
        # to ensure absolute control over the schema and prompt structure.
        # ---------------------------------------------------------
        try:
            # 1. Force ChromaDB to fetch schemas ONLY for the specified tables
            raw_ddls = vn.get_related_ddl(specific_tables)
            # logger.debug(f"Raw DDLs retrieved from Vanna:\n{raw_ddls}\n")
            step_schema_context = _filter_related_ddls(raw_ddls, specific_tables)

            # 2. Fetch related business rules/docs using the task description
            # If nothing is found, it returns an empty string or list
            related_docs = vn.get_related_documentation(clean_step_text)
            docs_text = "\n".join(related_docs) if isinstance(related_docs, list) else related_docs
            
            # 3. Fetch similar historical SQL queries
            similar_sqls = vn.get_similar_question_sql(clean_step_text)
            sqls_text = "\n".join([f"Question: {s['question']}\nSQL: {s['sql']}" for s in similar_sqls]) if isinstance(similar_sqls, list) else similar_sqls

            # 4. Assemble the ultimate, highly-constrained prompt for Gemini
            vanna_prompt = f"""
            [Database Schema Context]
            ⚠️ ATTENTION: The Sample Data included in the schema below is strictly a microscopic preview just to demonstrate the data format and column types. It is INCOMPLETE and DOES NOT contain all possible values present in the actual database.
            {step_schema_context}
            
            [Business Documentation & Rules]
            {docs_text}
            
            [Similar SQL Examples]
            {sqls_text}
            
            [Task Details]
            {clean_step_text}

            [Strict Execution Rules]
            Write a Microsoft SQL Server query to accomplish the Task Details. 
            CRITICAL RULE 1: You MUST ONLY use the tables listed here: {specific_tables}. Do NOT invent tables or columns.
            CRITICAL RULE 2 (DATA PIPELINE & GRANULARITY): 
            - If the task asks you to "Identify" specific targets (e.g., "identify the worst", "find the top 3 categories"), you MUST use `SELECT TOP N` to strictly limit the returned rows to ONLY those requested targets. Otherwise, if the task does not specify you can return all relevant rows.
            - KEY REQUIREMENT: Your SELECT statement MUST explicitly select the primary/foreign KEY column (e.g., ChannelKey, ProductKey) alongside the metrics, SO LONG AS the grouping grain allows it.
            - EXCEPTION (GRANULARITY PRESERVATION): If the task requires you to GROUP BY a higher-level dimensional attribute that only exists as a Name/Label (lacking a specific Key in the schema), DO NOT force a lower-level Key into the SELECT clause. Doing so will fracture the aggregation granularity. Instead, explicitly SELECT and return the higher-level Name/Label column to preserve the requested granularity for downstream systems.
            CRITICAL RULE 3 (GROUP BY SYNTAX): 
            - You MUST ONLY use actual database column names in your GROUP BY clause. NEVER use string literals or constants (e.g., `GROUP BY 'Online'` is STRICTLY FORBIDDEN).
            Return ONLY the SQL code without markdown wrappers if possible.
            CRITICAL RULE 4 (UNION & ORDER BY SYNTAX): 
            - In T-SQL, if you use UNION or UNION ALL and need to apply ORDER BY to the individual queries (such as when using TOP N), you MUST wrap each individual SELECT statement inside a subquery. 
            - Example of REQUIRED syntax: `SELECT * FROM (SELECT TOP 5 ... ORDER BY ...) AS T1 UNION ALL SELECT * FROM (SELECT TOP 5 ... ORDER BY ...) AS T2`. DO NOT put ORDER BY directly before a UNION keyword.
            """
            
            # 5. Submit to LLM for SQL generation
            logger.debug(f"Final Prompt for Gemini:\n{vanna_prompt}\n")
            generated_sql = vn.submit_prompt(vanna_prompt)
            # logger.debug(f"Raw SQL generated by Gemini:\n{generated_sql}\n")

            # Clean markdown wrappers (```sql ... ```) if the LLM adds them
            clean_sql = re.sub(r'```sql\n(.*?)\n```', r'\1', generated_sql, flags=re.DOTALL).strip()
            # logger.debug(f"Cleaned SQL after removing markdown wrappers:\n{clean_sql}\n")
            
            # Handle standard markdown blocks (``` ... ```)
            clean_sql = re.sub(r'```\n(.*?)\n```', r'\1', clean_sql, flags=re.DOTALL).strip()
            
            logger.info(f"Generated SQL for Step {current_step_num}:\n{clean_sql}")
            
            # ---------------------------------------------------------
            # PHASE 5: Execution & Memory Storage
            # ---------------------------------------------------------
            MAX_RETRIES = 2
            attempt = 0
            success = False
            result_df = None

            while attempt <= MAX_RETRIES and not success:
                try:
                    result_df = vn.run_sql(clean_sql)
                    success = True
                    
                    if attempt > 0:
                        logger.info(f"✅ Self-correction successful on attempt {attempt}!")
                        
                except Exception as e:
                    attempt += 1
                    error_msg = str(e)
                    logger.warning(f"⚠️ SQL Execution failed on Step {current_step_num}, attempt {attempt}. Error: {error_msg}")
                    
                    if attempt > MAX_RETRIES:
                        logger.error(f"❌ Max retries reached. Failing Step {current_step_num}.")
                        return {"error": f"Failed at Step {current_step_num} after {MAX_RETRIES} retries", "details": error_msg}
                    
                    logger.info(f"🔄 Triggering LLM Self-Correction (Attempt {attempt})...")                    

                    if attempt == 1:
                        logger.info(" SQL fixing without schema....")
                        correction_prompt = f"""
                        [CRITICAL SQL FIX]
                        The following Microsoft SQL Server query failed.
                        
                        [ORIGINAL TASK GOAL]:
                        {clean_step_text} 
                        
                        [ERROR]: {error_msg}
                        
                        [FAILED SQL]: 
                        {clean_sql}
                        
                        [STRICT INSTRUCTIONS]:
                        1. Analyze the FAILED SQL and the ERROR message to identify the root cause of the failure.
                        2. Fix the query so it executes successfully AND accurately accomplishes the ORIGINAL TASK GOAL.
                        3. DO NOT change any table names or column names. Work with the exact entities provided in the failed SQL.
                        4. Ensure the corrected syntax strictly complies with Microsoft SQL Server (T-SQL) standards.
                        5. Return ONLY the corrected SQL Server code without markdown wrappers. No explanation.
                        """
                    else:
                        logger.info(" SQL fixing with schema....")
                        correction_prompt = f"""
                        The Microsoft SQL Server query failed again after a previous fix attempt.
                        
                        [ORIGINAL TASK GOAL]:
                        {clean_step_text}
                        
                        [ERROR MESSAGE]: {error_msg}
                        
                        [FAILED SQL QUERY]:
                        {clean_sql}
                        
                        [ORIGINAL SCHEMA & RULES]:
                        {vanna_prompt}
                        
                        [STRICT INSTRUCTIONS]:
                        1. Analyze the FAILED SQL and the ERROR message to identify the root cause.
                        2. Cross-reference your logic with the ORIGINAL SCHEMA to ensure you are ONLY using valid tables and columns.
                        3. Fix the query so it executes successfully AND accurately accomplishes the ORIGINAL TASK GOAL.
                        4. Ensure the corrected syntax strictly complies with Microsoft SQL Server (T-SQL) standards.
                        5. Return ONLY the corrected SQL Server code without markdown wrappers. No explanation.
                        """
                    
                    logger.debug(f"Correction Prompt for Gemini:\n{correction_prompt}\n")
                    raw_sql = vn.submit_prompt(correction_prompt)
                    clean_sql = raw_sql.replace("```sql", "").replace("```", "").strip()
                    logger.info(f"🛠️ Corrected SQL for Step {current_step_num}:\n{clean_sql}")

            if success and result_df is not None:
                step_results_memory[current_step_num] = result_df
                logger.debug(f"Step {current_step_num} Results Stored:\n{result_df}\n")
            
        except Exception as e:
            logger.error(f"Execution failed at Step {current_step_num}: {str(e)}")
            return {"error": f"Failed at Step {current_step_num}", "details": str(e)}

    # ---------------------------------------------------------
    # PHASE 6: Payload Delivery
    # Return the data from the final step to the Orchestrator/SqlAgent
    # ---------------------------------------------------------
    if step_results_memory:
        all_data_payload = {}
        
        for step_num, df in step_results_memory.items():
            all_data_payload[f"step_{step_num}"] = df.head(100).to_dict(orient='records')
        
        logger.debug(f"Final Data Payload to return:\n{all_data_payload}\n")

        return {
            "status": "success",
            "message": "All steps executed successfully.",
            "data": all_data_payload
        }
    
    return {"error": "Execution completed, but no final data was produced."}

def _filter_related_ddls(raw_ddls, specific_tables: str) -> str:
    """
    Helper function to strictly filter Vanna's retrieved DDLs.
    It prevents the "Foreign Key Trap" by specifically looking for the 
    'CREATE TABLE [schema].[tablename](' statement, rather than searching 
    the entire DDL script.
    
    Returns: A single string containing the combined, filtered DDLs.
    """
    # 1. Clean and extract full table names WITH schema (e.g., 'dbo.factsales')
    clean_table_str = specific_tables.replace("- Tables Used:", "").strip()
    target_table_list = [t.strip().lower() for t in clean_table_str.split(",") if t.strip()]
    
    # 2. STRICT FILTERING: Exact match on CREATE TABLE statement
    filtered_ddls = []
    if isinstance(raw_ddls, list):
        for ddl in raw_ddls:
            # Remove brackets to normalize the text: "[dbo].[FactSales]" -> "dbo.factsales"
            clean_ddl = ddl.lower().replace('[', '').replace(']', '')
            
            keep_ddl = False
            for target_table in target_table_list:
                # [CRITICAL FIX] We ONLY search for the exact CREATE TABLE declaration.
                # E.g., looking specifically for: "create table dbo.factsales(" or "create table dbo.factsales ("
                # This explicitly ignores Foreign Key "REFERENCES dbo.target_table" at the bottom of the script.
                pattern = rf"create table\s+{re.escape(target_table)}\s*\("
                
                if re.search(pattern, clean_ddl):
                    keep_ddl = True
                    break  # Found exact match, keep this DDL and stop checking other targets
                    
            if keep_ddl:
                filtered_ddls.append(ddl)
    else:
        # Fallback just in case Vanna returns a single raw string
        filtered_ddls.append(str(raw_ddls))
                    
    logger.info(f"Schema strictly filtered. Reduced DDL count to {len(filtered_ddls)} based on exact targets: {target_table_list}")

    # 3. Combine the filtered DDLs into a single context string
    return "\n\n".join(filtered_ddls)